name: CI
on: [pull_request]

jobs:
  fail:
    name: fail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Fail
        run: ./fail
      - name: next
        run: echo hello
